"use client";

import { useState } from "react";

function ConceptCard({
  title,
  subtitle,
  from,
  to,
  fromLabel,
  toLabel,
  description,
  color,
}: {
  title: string;
  subtitle: string;
  from: string;
  to: string;
  fromLabel: string;
  toLabel: string;
  description: string;
  color: string;
}) {
  const [revealed, setRevealed] = useState(false);
  const colorMap: Record<string, string> = {
    orange: "from-orange-500/20 to-orange-600/5 border-orange-500/30",
    blue: "from-blue-500/20 to-blue-600/5 border-blue-500/30",
    emerald: "from-emerald-500/20 to-emerald-600/5 border-emerald-500/30",
  };
  const accentMap: Record<string, string> = {
    orange: "text-orange-400",
    blue: "text-blue-400",
    emerald: "text-emerald-400",
  };
  const dotMap: Record<string, string> = {
    orange: "bg-orange-500",
    blue: "bg-blue-500",
    emerald: "bg-emerald-500",
  };

  return (
    <div
      className={`bg-gradient-to-b ${colorMap[color]} border rounded-2xl p-6 flex flex-col gap-4`}
    >
      <div className="flex items-center gap-2">
        <div className={`w-2 h-2 rounded-full ${dotMap[color]}`} />
        <h3 className="text-white font-semibold">{title}</h3>
      </div>
      <p className="text-xs text-slate-400">{subtitle}</p>

      <div className="flex flex-col items-center gap-3 py-4">
        <div className="w-full bg-slate-800/80 rounded-lg px-4 py-3 text-center">
          <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">
            {fromLabel}
          </p>
          <p className="font-mono text-sm text-white tracking-wider">
            {revealed ? from : from.slice(0, 4) + " **** **** " + from.slice(-4)}
          </p>
        </div>

        <div className="flex flex-col items-center">
          <div className={`w-0.5 h-6 ${dotMap[color]} opacity-40`} />
          <svg
            className={`w-5 h-5 ${accentMap[color]}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M19 14l-7 7m0 0l-7-7m7 7V3"
            />
          </svg>
        </div>

        <div
          className={`w-full bg-slate-800/80 rounded-lg px-4 py-3 text-center border border-dashed ${
            color === "orange"
              ? "border-orange-500/30"
              : color === "blue"
              ? "border-blue-500/30"
              : "border-emerald-500/30"
          }`}
        >
          <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-1">
            {toLabel}
          </p>
          <p className={`font-mono text-sm ${accentMap[color]} tracking-wider`}>
            {revealed ? to : to.slice(0, 4) + " **** **** " + to.slice(-4)}
          </p>
        </div>
      </div>

      <button
        onClick={() => setRevealed(!revealed)}
        className="text-xs text-slate-500 hover:text-slate-300 transition-colors self-center"
      >
        {revealed ? "Mask Numbers" : "Reveal Numbers"}
      </button>

      <p className="text-xs text-slate-400 leading-relaxed">{description}</p>
    </div>
  );
}

function FlowStep({
  label,
  active,
  last,
}: {
  label: string;
  active?: boolean;
  last?: boolean;
}) {
  return (
    <div className="flex items-center gap-3">
      <div
        className={`w-10 h-10 rounded-full flex items-center justify-center border-2 shrink-0 ${
          active
            ? "border-orange-500 bg-orange-500/20"
            : "border-slate-700 bg-slate-800"
        }`}
      >
        <div
          className={`w-3 h-3 rounded-full ${
            active ? "bg-orange-500" : "bg-slate-600"
          }`}
        />
      </div>
      <span
        className={`text-sm ${active ? "text-white font-medium" : "text-slate-400"}`}
      >
        {label}
      </span>
      {!last && (
        <div className="hidden sm:block flex-1 h-px bg-slate-800 ml-2" />
      )}
    </div>
  );
}

export default function LearnMode() {
  return (
    <div className="space-y-12 animate-fade-in">
      {/* Concept Cards */}
      <section>
        <h2 className="text-2xl font-bold text-white mb-2">
          How Tokenization Works
        </h2>
        <p className="text-slate-400 mb-8">
          Three key transformations that protect cardholder data
        </p>
        <div className="grid md:grid-cols-3 gap-6">
          <ConceptCard
            title="Gateway Token"
            subtitle="Card to Gateway Token"
            from="5123 4500 0000 0008"
            to="9876 5432 1098 7654"
            fromLabel="Card Number (PAN)"
            toLabel="Gateway Token"
            description="A random token generated by the Mastercard Gateway. Maps to the real card in a secure vault. Used for stored credentials, subscriptions, and merchant-initiated transactions."
            color="orange"
          />
          <ConceptCard
            title="Network Token"
            subtitle="Card to Network Token (DPAN)"
            from="5123 4500 0000 0008"
            to="5246 8900 0012 3456"
            fromLabel="Funding PAN (FPAN)"
            toLabel="Device PAN (DPAN)"
            description="A token provisioned by the card network's Token Service Provider (TSP). Auto-updates when cards expire. Provides higher approval rates and enhanced security."
            color="blue"
          />
          <ConceptCard
            title="Token Payment"
            subtitle="Token to Future Payment"
            from="9876 5432 1098 7654"
            to="AUTH CODE: 123456"
            fromLabel="Stored Token"
            toLabel="Payment Authorized"
            description="Once tokenized, future payments use the token instead of the card number. No PAN is stored or transmitted by the merchant. Reduces PCI scope."
            color="emerald"
          />
        </div>
      </section>

      {/* Payment Flow */}
      <section>
        <h2 className="text-xl font-bold text-white mb-2">Payment Flow</h2>
        <p className="text-slate-400 mb-6">
          How data moves through the tokenization system
        </p>
        <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-8">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 sm:gap-0 justify-between">
            {[
              { label: "Customer", desc: "Enters card details" },
              { label: "Merchant", desc: "Sends to gateway" },
              { label: "Gateway", desc: "Tokenizes card" },
              { label: "Token Vault", desc: "Stores mapping" },
              { label: "Card Network", desc: "Processes payment" },
            ].map((step, i) => (
              <div key={step.label} className="flex items-center gap-3 sm:flex-col sm:gap-2 sm:text-center flex-1">
                <div
                  className={`w-12 h-12 rounded-xl flex items-center justify-center text-lg font-bold shrink-0 ${
                    i === 0
                      ? "bg-blue-500/20 text-blue-400 border border-blue-500/30"
                      : i === 3
                      ? "bg-orange-500/20 text-orange-400 border border-orange-500/30"
                      : "bg-slate-800 text-slate-400 border border-slate-700"
                  }`}
                >
                  {i + 1}
                </div>
                <div>
                  <p className="text-sm font-medium text-white">{step.label}</p>
                  <p className="text-xs text-slate-500">{step.desc}</p>
                </div>
                {i < 4 && (
                  <div className="hidden sm:block w-full h-px bg-gradient-to-r from-slate-700 to-slate-800 mx-2" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Timeline */}
      <section>
        <h2 className="text-xl font-bold text-white mb-2">
          Transaction Timeline
        </h2>
        <p className="text-slate-400 mb-6">
          From first payment to recurring charges
        </p>
        <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-8">
          <div className="flex flex-col gap-6">
            <FlowStep label="Card entered by customer (CIT)" active />
            <FlowStep label="Gateway token created and stored" active />
            <FlowStep label="Token mapped in secure vault" active />
            <FlowStep label="Future payment charged using token (MIT)" active />
            <FlowStep label="No card number transmitted" active last />
          </div>
        </div>
      </section>

      {/* Token Vault Visualization */}
      <section>
        <h2 className="text-xl font-bold text-white mb-2">
          Token Vault: PCI Scope Reduction
        </h2>
        <p className="text-slate-400 mb-6">
          What the merchant stores vs. what the vault stores
        </p>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-6">
            <h3 className="text-red-400 font-semibold text-sm mb-4 uppercase tracking-wider">
              Without Tokenization
            </h3>
            <div className="font-mono text-xs space-y-2">
              <div className="bg-slate-900 rounded-lg p-3 border border-red-500/10">
                <span className="text-slate-500">Customer ID:</span>{" "}
                <span className="text-white">C-1001</span>
              </div>
              <div className="bg-slate-900 rounded-lg p-3 border border-red-500/10">
                <span className="text-slate-500">Card Number:</span>{" "}
                <span className="text-red-400">5123 4500 0000 0008</span>
              </div>
              <div className="bg-slate-900 rounded-lg p-3 border border-red-500/10">
                <span className="text-slate-500">Expiry:</span>{" "}
                <span className="text-red-400">05/25</span>
              </div>
            </div>
            <p className="text-xs text-red-400/60 mt-4">
              Full PCI DSS compliance required
            </p>
          </div>
          <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-2xl p-6">
            <h3 className="text-emerald-400 font-semibold text-sm mb-4 uppercase tracking-wider">
              With Tokenization
            </h3>
            <div className="font-mono text-xs space-y-2">
              <div className="bg-slate-900 rounded-lg p-3 border border-emerald-500/10">
                <span className="text-slate-500">Customer ID:</span>{" "}
                <span className="text-white">C-1001</span>
              </div>
              <div className="bg-slate-900 rounded-lg p-3 border border-emerald-500/10">
                <span className="text-slate-500">Token:</span>{" "}
                <span className="text-emerald-400">9876543210987654</span>
              </div>
              <div className="bg-slate-900 rounded-lg p-3 border border-emerald-500/10">
                <span className="text-slate-500">Card Number:</span>{" "}
                <span className="text-slate-600">Not stored</span>
              </div>
            </div>
            <p className="text-xs text-emerald-400/60 mt-4">
              Reduced PCI scope - token is not sensitive data
            </p>
          </div>
        </div>
      </section>

      {/* Network Token Advantage */}
      <section>
        <h2 className="text-xl font-bold text-white mb-2">
          Network Token: Auto Card Update
        </h2>
        <p className="text-slate-400 mb-6">
          When a card expires, the network token is automatically updated
        </p>
        <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-8">
          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center space-y-3">
              <div className="w-14 h-14 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center justify-center mx-auto">
                <span className="text-red-400 font-bold">!</span>
              </div>
              <h4 className="text-white font-medium">Card Expires</h4>
              <p className="text-xs text-slate-400">
                Physical card 5123 **** 0008 reaches expiry date 05/25
              </p>
            </div>
            <div className="text-center space-y-3">
              <div className="w-14 h-14 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center mx-auto">
                <svg className="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
              </div>
              <h4 className="text-white font-medium">TSP Auto-Updates</h4>
              <p className="text-xs text-slate-400">
                Token Service Provider updates the network token with new card details
              </p>
            </div>
            <div className="text-center space-y-3">
              <div className="w-14 h-14 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto">
                <svg className="w-6 h-6 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h4 className="text-white font-medium">Payment Continues</h4>
              <p className="text-xs text-slate-400">
                Recurring payments succeed without merchant intervention
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
